package:
  name: clickhouse
  version: 23.10.3.5
  epoch: 0
  description: ClickHouse is the fastest and most resource efficient open-source database for real-time apps and analytics.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - ninja
      - build-base
      - cmake
      - clang-17
      - clang-17-dev
      - coreutils
      - grep
      - bash
      - python3
      - yasm
      - nasm
      - llvm-lld-17
      - llvm-lld-17-dev
      - llvm-libcxx-17
      - llvm-libcxx-17-dev
      - perl
      - findutils

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ClickHouse/ClickHouse
      tag: v${{package.version}}-stable
      expected-commit: b2ba7637a414ab9442e920e9ad99bd89aa6aca88

  # The default build script is defensive and tries to protect against defining cflags.
  - uses: patch
    with:
      patches: allow_cflags.patch

  - runs: |
      git submodule update --init
      mkdir build
      cd build
      cmake \
        -DCOMPILER_CACHE=disabled \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_LIBDIR=lib \
        ..

  - runs: |
      cd build
      ninja -j $(nproc)
      DESTDIR=${{targets.destdir}} ninja install

      rm -rf ${{targets.destdir}}/usr/lib/debug

  - uses: strip

subpackages:
  - name: "clickhouse-dev"
    description: "headers for clickhouse"
    pipeline:
      - uses: split/dev

  - name: "clickhouse-bash-completion"
    description: "bash completion for clickhouse"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share/bash-completion/completions
          mv ${{targets.destdir}}/usr/share/bash-completion/completions/clickhouse ${{targets.subpkgdir}}/usr/share/bash-completion/completions

update:
  enabled: true
  github:
    identifier: ClickHouse/ClickHouse
    strip-prefix: v
    strip-suffix: -stable
