package:
  name: ggshield
  version: 1.19.1
  epoch: 1
  description: Find and fix 360+ types of hardcoded secrets and 70+ types of infrastructure-as-code misconfigurations.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools
      - py3-wheel
      - py3-pip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/GitGuardian/ggshield
      tag: v${{package.version}}
      expected-commit: 3fc47e578bf02c906b8a437a08ec350968a58b8d

  - runs: |
      pip3 install certifi -U  # https://github.com/advisories/GHSA-xqr8-7jwr-rhp7
      python3 setup.py bdist_wheel
      pip3 install . --prefix=/usr --root="${{targets.destdir}}"
      find ${{targets.destdir}} -name "*.pyc" -exec rm -rf '{}' +

  - uses: strip

update:
  enabled: true
  github:
    identifier: GitGuardian/ggshield
    use-tag: true
    strip-prefix: v
