package:
  name: ko
  version: 0.15.0
  epoch: 2
  description: Simple, fast container image builder for Go applications.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      destination: ko
      expected-commit: 31035ad2026bfbafaa4f009baefe72463af1b3a7
      repository: https://github.com/ko-build/ko
      tag: v${{package.version}}

  - uses: go/build
    with:
      deps: google.golang.org/grpc@v1.58.3
      ldflags: -w -X github.com/google/ko/pkg/commands.Version=${{package.version}}
      modroot: ko
      output: ko
      packages: .
      vendor: true

  - runs: |
      echo hello > ${{targets.destdir}}/hello.txt

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: ko-build/ko
    strip-prefix: v
