package:
  name: numpy
  version: 1.26.0
  epoch: 2
  description: "The fundamental package for scientific computing with Python."
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - python3
      - build-base
      - git
      - bash
      - meson
      - cython
      - python3-dev
      - py3-gpep517
      - py3-packaging
      - py3-setuptools
      - py3-wheel
      - gfortran
      - py3-pip
      - openblas-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/numpy/numpy
      tag: v${{package.version}}
      expected-commit: d35cd07ea997f033b2d89d349734c61f5de54b0d

  - runs: |
      git submodule update --init

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

subpackages:
  - name: f2py
    description: "f2py for numpy (for python3)"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/f2py* "${{targets.subpkgdir}}"/usr/bin
    dependencies:
      runtime:
        - python3-dev
        - numpy

update:
  enabled: true
  github:
    identifier: numpy/numpy
    # There are some v2 pre-releases
    tag-filter: v1
    strip-prefix: v
    strip-suffix: .dev0
