package:
  name: poetry
  version: 1.6.1
  epoch: 3
  description: "Python packaging and dependency management made easy"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - python3
      - py3-pip
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/python-poetry/poetry/archive/${{package.version}}.tar.gz
      expected-sha256: 5653d6905c378703089fb500f7a85b58bf3b439c61cabb377a11df5495407f9f

  - runs: |
      pip install . --prefix=/usr --root=${{targets.destdir}}
      # Remove everything in /usr/bin except poetry
      find "${{targets.destdir}}/usr/bin" -type f -not -name poetry -delete
      find ${{targets.destdir}} -name "*.pyc" -exec rm -rf '{}' +

  - uses: strip

update:
  enabled: true
  github:
    identifier: python-poetry/poetry
