package:
  name: py3-tensorflow-serving-api
  version: 2.13.1
  epoch: 1
  description: A flexible, high-performance serving system for machine learning models
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-grpcio
      - tensorflow-core
      - py3-tensorflow-core
      - py3-protobuf
      - python-3

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python-3
      - py3-build
      - py3-installer
      - py3-setuptools
      - py3-wheel
      - py3-pip
      - git
      - bazel-6
      - openjdk-17
      - openjdk-17-jre
      - bash
      - numpy
      - patch
      - automake
      - autoconf
  environment:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk

pipeline:
  - uses: git-checkout
    with:
      expected-commit: ae482b9dd12bf8dde38dd91a384a85f96a5fc09c
      repository: https://github.com/tensorflow/serving
      tag: ${{package.version}}

  - runs: |
      bazel build --verbose_failures -c opt tensorflow_serving/tools/pip_package:build_pip_package
      sed -i "s|bazel-genfiles/|bazel-out/k8-opt/bin/|g" tensorflow_serving/tools/pip_package/build_pip_package.sh
      mkdir -p dist
      srcdir=$(pwd)
      bazel-bin/tensorflow_serving/tools/pip_package/build_pip_package "${srcdir}/dist"

      pip install --root ${{targets.destdir}} dist/tensorflow_serving_api*.whl
      install -Dm644 LICENSE "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE
      find ${{targets.destdir}} -name "*.pyc" -exec rm -rf '{}' +

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: tensorflow/serving
