package:
  name: py3-pipenv
  version: 2023.10.3
  epoch: 1
  description: "Pipenv is a Python virtualenv management tool that supports a multitude of systems and nicely bridges the gaps between pip, python (using system python, pyenv or asdf) and virtualenv."
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-pip

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypa/pipenv
      tag: v${{package.version}}
      expected-commit: 71efe85d8986a73239d573bb563f9373d9ce03db

  - runs: |
      pip install . --prefix=/usr --root=${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - '.*\.dev.*'
  github:
    identifier: pypa/pipenv
    use-tag: true
    strip-prefix: v
