package:
  name: py3-ml-metadata
  version: 1.14.0
  epoch: 1
  description: For recording and retrieving metadata associated with ML developer and data scientist workflows.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-setuptools
      - cmake
      - bazel-5
      - openjdk-11
      - bash
      - patch
      - openssl-dev
      - python3-dev
  environment:
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/google/ml-metadata
      tag: v${{package.version}}
      expected-commit: 4893bf12d763278a05867b61a47a478ed1286289

  - uses: patch
    with:
      series: series

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --skip-build --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: google/ml-metadata
    use-tag: true
    strip-prefix: v
